name: Update Comparison List (Latest)

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * *

jobs:
  list_generate:
    name: List Generate
    runs-on: ubuntu-latest
    steps:
      - name: Run update langauge script 
        run: python .github/scripts/update-language.py

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
