name: Update Comparison List (Latest)

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * 1

permissions:
  contents: read

jobs:
  list_generate:
    name: List Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checking Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Run update langauge script
        id: mc
        run: python .github/scripts/update-language.py

      - name: Commit & Push changes
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: "chore: 更新 Minecraft ${{ steps.mc.outputs.mc_version }} 對照表"
